export type { FingeringOverlayProps } from './fingering-overlay'
export { FingeringOverlay, fingeringOverlayVariants } from './fingering-overlay'
export type { InteractivePianoProps, SelectedChord } from './interactive-piano'
export { InteractivePiano } from './interactive-piano'
export type { PianoControlsProps } from './piano-controls'
export { PianoControls } from './piano-controls'
export type { FingerNumber, PianoKeyProps } from './piano-key'
export { PianoKey, pianoKeyVariants } from './piano-key'
export type { PianoKeyboardProps } from './piano-keyboard'
export { PianoKeyboard } from './piano-keyboard'
